### ISSUE TITLE
7.0系统启动插件找不到资源 AppCompatActivity

### ISSUE THREAD

**Issue by ftyan805614** [froyohuang/RePlugin-AndroidX#11]

**Comment by drachuojin** [comment]
求解

**Comment by froyohuang** [comment]
> _No description provided._

有更详细的报错信息么

**Comment by froyohuang** [comment]
> 求解

有更详细的报错信息么

**Comment by o19871109** [comment]
Caused by: android.content.res.Resources$NotFoundException: Drawable com.qihoo360.replugin.sample.host:id/dialog_button with resource ID #0x7f07005c
     Caused by: android.content.res.Resources$NotFoundException: Resource "com.qihoo360.replugin.sample.host:id/dialog_button" (7f07005c) is not a Drawable (color or path): TypedValue{t=0x12/d=0x0 a=4 r=0x7f07005c}
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:890)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:732)
